// This file is the single source of truth for the PDF field names.
// Field names are the AcroForm names exported by `npm run inspect:pdf` for
// public/templates/shouhei-riyusho.pdf.

export const pdfFieldNames = [
  'Text1',
  'Text2',
  'Text3',
  'Text4',
  'Text5',
  'Text6',
  'Text7',
  'Text8',
  'Text9',
  'Text10',
  'Text11',
  'Text12',
  'Text13',
  'Text14',
  'Text15',
  'Text16',
  'Text17',
  'Check Box1',
  'Check Box2',
  'Text18',
  'Text19',
  'Text20',
  'Text21',
  'Text22',
  'Text23',
  'Text24',
  'Text25',
  'Text26',
] as const;

export const invitationReasonPdfFields = {
  documentDateEra: 'Text1',
  documentDateYear: 'Text2',
  documentDateMonth: 'Text3',
  documentDateDay: 'Text4',
  diplomaticMission: 'Text5',
  inviterPostalCodeFirst3: 'Text6',
  inviterPostalCodeLast4: 'Text7',
  inviterAddress: 'Text8',
  inviterName: 'Text9',
  inviterPhone: 'Text10',
  inviterExtension: 'Text11',
  organisationName: 'Text12',
  contactPersonName: 'Text13',
  contactPhone: 'Text14',
  contactExtension: 'Text15',
  applicantNationality: 'Text16',
  applicantOccupation: 'Text17',
  applicantPassportName: 'Text18',
  applicantGenderMale: 'Check Box1',
  applicantGenderFemale: 'Check Box2',
  applicantGenderOtherText: 'Text19',
  applicantDateOfBirthYear: 'Text20',
  applicantDateOfBirthMonth: 'Text21',
  applicantDateOfBirthDay: 'Text22',
  applicantAge: 'Text23',
  invitationPurpose: 'Text24',
  invitationBackground: 'Text25',
  relationshipToApplicant: 'Text26',
} as const;

export type PdfFieldName = (typeof pdfFieldNames)[number];
export type InvitationReasonPdfFieldKey = keyof typeof invitationReasonPdfFields;
