import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { PDFDocument } from 'pdf-lib';

const templatePath = path.join(process.cwd(), 'public', 'templates', 'shouhei-riyusho.pdf');
const outputPath = path.join(process.cwd(), 'src', 'lib', 'pdfFieldNames.ts');

const semanticKeys = [
  'documentDateEra',
  'documentDateYear',
  'documentDateMonth',
  'documentDateDay',
  'diplomaticMission',
  'inviterPostalCodeFirst3',
  'inviterPostalCodeLast4',
  'inviterAddress',
  'inviterName',
  'inviterPhone',
  'inviterExtension',
  'organisationName',
  'contactPersonName',
  'contactPhone',
  'contactExtension',
  'applicantNationality',
  'applicantOccupation',
  'applicantPassportName',
  'applicantGenderMale',
  'applicantGenderFemale',
  'applicantGenderOtherText',
  'applicantDateOfBirthYear',
  'applicantDateOfBirthMonth',
  'applicantDateOfBirthDay',
  'applicantAge',
  'invitationPurpose',
  'invitationBackground',
  'relationshipToApplicant',
] as const;

function toConstantName(fieldName: string, index: number, usedNames: Set<string>) {
  const asciiName = fieldName
    .normalize('NFKD')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase();
  const baseName = asciiName.length > 0 ? asciiName : 'FIELD';
  let constantName = baseName;
  let suffix = index + 1;

  while (usedNames.has(constantName)) {
    constantName = `${baseName}_${suffix}`;
    suffix += 1;
  }

  usedNames.add(constantName);
  return constantName;
}

function buildOutput(fieldNames: string[]) {
  const entries = fieldNames.map((name) => `  ${JSON.stringify(name)},`).join('\n');
  const usedConstantNames = new Set<string>();
  const objectEntries = fieldNames
    .map((name, index) => `  ${toConstantName(name, index, usedConstantNames)}: ${JSON.stringify(name)},`)
    .join('\n');
  const semanticEntries = semanticKeys.map((key) => `  ${key}: '',`).join('\n');

  return `// This file is generated by \`npm run inspect:pdf\`.
// Do not guess field names; update semantic values below from the actual PDF template.

export const pdfFieldNames = [
${entries}
] as const;

export const pdfFieldNameMap = {
${objectEntries}
} as const;

export const invitationReasonPdfFields = {
${semanticEntries}
} as const;

export type PdfFieldName = (typeof pdfFieldNames)[number];
export type InvitationReasonPdfFieldKey = keyof typeof invitationReasonPdfFields;
`;
}

async function main() {
  let pdfBytes: Uint8Array;

  try {
    pdfBytes = await readFile(templatePath);
  } catch (error) {
    console.error(`PDF template was not found at ${templatePath}`);
    console.error('Place the template at public/templates/shouhei-riyusho.pdf and run this script again.');
    process.exitCode = 1;
    return;
  }

  const pdfDoc = await PDFDocument.load(pdfBytes);
  const fieldNames = pdfDoc.getForm().getFields().map((field) => field.getName());

  if (fieldNames.length === 0) {
    console.log('No AcroForm fields were found in public/templates/shouhei-riyusho.pdf.');
    console.log('This means there are no field names to export. Do not use guessed or coordinate-based names in this step.');
    return;
  }

  console.log('AcroForm field names:');
  for (const name of fieldNames) {
    console.log(name);
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, buildOutput(fieldNames), 'utf8');
  console.log(`\nUpdated ${path.relative(process.cwd(), outputPath)} with ${fieldNames.length} field name(s).`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
