import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { PDFDocument, PDFCheckBox, PDFDropdown, PDFOptionList, PDFRadioGroup, PDFTextField } from 'pdf-lib';
import type { PDFField } from 'pdf-lib';

const templatePath = path.join(process.cwd(), 'public', 'templates', 'shouhei-riyusho.pdf');
const outputPath = path.join(process.cwd(), 'src', 'lib', 'pdfFieldNames.ts');
const docsPath = path.join(process.cwd(), 'docs', 'pdf-field-inspection.md');

const semanticKeys = [
  'documentDateYear',
  'documentDateMonth',
  'documentDateDay',
  'diplomaticMission',
  'inviterPostalCodeFirst3',
  'inviterPostalCodeLast4',
  'inviterAddress',
  'inviterName',
  'inviterPhone',
  'inviterExtension',
  'organisationName',
  'contactPersonName',
  'contactPhone',
  'contactExtension',
  'applicantNationality',
  'applicantOccupation',
  'applicantPassportName',
  'applicantGenderMale',
  'applicantGenderFemale',
  'additionalApplicantsCount',
  'applicantDateOfBirthYear',
  'applicantDateOfBirthMonth',
  'applicantDateOfBirthDay',
  'applicantAge',
  'invitationPurpose',
  'invitationBackground',
  'relationshipToApplicant',
] as const;

const semanticFieldMappings: Record<(typeof semanticKeys)[number], string> = {
  documentDateYear: '日付＿年',
  documentDateMonth: '日付＿月',
  documentDateDay: '日付＿日',
  diplomaticMission: '公館名',
  inviterPostalCodeFirst3: '郵便番号１',
  inviterPostalCodeLast4: '郵便番号２',
  inviterAddress: '住所1',
  inviterName: '氏名',
  inviterPhone: '招聘人＿電話番号',
  inviterExtension: '招聘人＿内線番号',
  organisationName: '担当者所属先名',
  contactPersonName: '担当者氏名',
  contactPhone: '担当者電話番号',
  contactExtension: '担当者＿内線番号',
  applicantNationality: '国籍',
  applicantOccupation: '職業',
  applicantPassportName: 'ビザ申請人＿氏名',
  applicantGenderMale: 'toggle_2',
  applicantGenderFemale: 'toggle_3',
  additionalApplicantsCount: 'ほか',
  applicantDateOfBirthYear: '生年月日＿西暦',
  applicantDateOfBirthMonth: '生年月日＿月',
  applicantDateOfBirthDay: '生年月日＿日',
  applicantAge: '生年月日＿歳',
  invitationPurpose: '招聘目的',
  invitationBackground: '招聘経緯',
  relationshipToApplicant: '申請人との関係',
};

type WidgetReport = {
  fieldName: string;
  fieldType: string;
  pageIndex: number | 'unknown';
  x: number;
  y: number;
  width: number;
  height: number;
};

function fieldType(field: PDFField) {
  if (field instanceof PDFTextField) return 'text';
  if (field instanceof PDFCheckBox) return 'checkbox';
  if (field instanceof PDFRadioGroup) return 'radio';
  if (field instanceof PDFDropdown) return 'dropdown';
  if (field instanceof PDFOptionList) return 'option-list';
  return field.constructor.name;
}

function toConstantName(fieldName: string, index: number, usedNames: Set<string>) {
  const asciiName = fieldName.normalize('NFKD').replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase();
  const baseName = asciiName.length > 0 && /^[A-Z_$]/.test(asciiName) ? asciiName : `FIELD_${asciiName}`;
  let constantName = baseName;
  let suffix = index + 1;
  while (usedNames.has(constantName)) {
    constantName = `${baseName}_${suffix}`;
    suffix += 1;
  }
  usedNames.add(constantName);
  return constantName;
}

function buildOutput(fieldNames: string[]) {
  const entries = fieldNames.map((name) => `  ${JSON.stringify(name)},`).join('\n');
  const usedConstantNames = new Set<string>();
  const objectEntries = fieldNames.map((name, index) => `  ${toConstantName(name, index, usedConstantNames)}: ${JSON.stringify(name)},`).join('\n');
  const semanticEntries = semanticKeys.map((key) => `  ${key}: ${JSON.stringify(semanticFieldMappings[key])},`).join('\n');

  return `// This file is generated by \`npm run inspect:pdf\`.
// Fill semantic mapping values only after verifying widget rectangles in docs/pdf-field-inspection.md.
// Do not guess field names or rely only on AcroForm order.

export const pdfFieldNames = [
${entries}
] as const;

export const pdfFieldNameMap = {
${objectEntries}
} as const;

export const invitationReasonPdfFields = {
${semanticEntries}
} as const;

export type PdfFieldName = (typeof pdfFieldNames)[number];
export type InvitationReasonPdfFieldKey = keyof typeof invitationReasonPdfFields;
`;
}

function rectFromWidget(widget: any) {
  const rectangle = typeof widget.getRectangle === 'function' ? widget.getRectangle() : undefined;
  if (rectangle) return rectangle;
  const rect = widget.dict?.lookup?.('Rect') ?? widget.dict?.get?.('Rect');
  const values = rect?.asArray?.().map((n: any) => n.asNumber?.() ?? Number(n));
  if (!values || values.length < 4) return { x: NaN, y: NaN, width: NaN, height: NaN };
  return { x: values[0], y: values[1], width: values[2] - values[0], height: values[3] - values[1] };
}

function buildMarkdown(reports: WidgetReport[]) {
  const rows = reports.map((r, i) => `| ${i + 1} | ${r.fieldName} | ${r.fieldType} | ${r.pageIndex} | ${r.x.toFixed(2)} | ${r.y.toFixed(2)} | ${r.width.toFixed(2)} | ${r.height.toFixed(2)} |`).join('\n');
  const completedMappingRows = semanticKeys.map((key) => `| \`${key}\` | \`${semanticFieldMappings[key]}\` | ${mappingDecision(key)} |`).join('\n');
  return `# PDF Field Inspection: 招へい理由書

Generated by \`npm run inspect:pdf\`.

## Mapping conclusions

- The PDF template file was inspected by AcroForm widget rectangle, not by field order alone.
- The fillable template at \`public/templates/shouhei-riyusho.pdf\` has been inspected and the mapping in \`src/lib/pdfFieldNames.ts\` is complete.
- \`documentDateEra\` is intentionally not part of the semantic model: the template prints the visible \`令和\` text and has only year/month/day widgets.
- \`additionalApplicantsCount\` is the \`ほか N 名\` field. The MVP always has exactly one applicant, so it must remain blank and must not be treated as gender.
- \`diplomaticMission\` maps to \`公館名\` at x=102.24, y=713.24, width=87.97. This widget is the blank after the printed \`在\` and before the printed \`日本国\`; therefore the value is \`上海\`, not \`在上海日本国総領事館\`.
- The inviter address is a single widget (\`住所1\` at x=189.48, y=608.48, width=297.84), so the semantic model remains \`inviterAddress\`.

## Completed semantic mapping decisions

| Semantic key | PDF field | Decision basis |
|---|---|---|
${completedMappingRows}

## Required semantic fields to verify

- Date: \`documentDateYear\`, \`documentDateMonth\`, \`documentDateDay\`
- Diplomatic mission: \`diplomaticMission\`
- Applicant: \`applicantNationality\`, \`applicantOccupation\`, \`applicantPassportName\`, \`applicantGenderMale\`, \`applicantGenderFemale\`, \`additionalApplicantsCount\`, \`applicantDateOfBirthYear\`, \`applicantDateOfBirthMonth\`, \`applicantDateOfBirthDay\`, \`applicantAge\`
- Inviter/organisation: \`inviterPostalCodeFirst3\`, \`inviterPostalCodeLast4\`, \`inviterAddress\`, \`inviterName\`, \`inviterPhone\`, \`inviterExtension\`, \`organisationName\`, \`contactPersonName\`, \`contactPhone\`, \`contactExtension\`
- Narrative: \`invitationPurpose\`, \`invitationBackground\`, \`relationshipToApplicant\`

## Visual order: top-to-bottom, left-to-right

| # | Field name | Type | Page | x | y | width | height |
|---:|---|---|---:|---:|---:|---:|---:|
${rows || '| | No AcroForm fields found or template missing. | | | | | | |'}
`;
}

function mappingDecision(key: (typeof semanticKeys)[number]) {
  const decisions: Record<(typeof semanticKeys)[number], string> = {
    documentDateYear: 'Top-right date year blank after printed `令和`; no separate era input widget exists.',
    documentDateMonth: 'Top-right date month blank.',
    documentDateDay: 'Top-right date day blank.',
    diplomaticMission: 'Blank between printed `在` and `日本国`, so sample data uses `上海` only.',
    inviterPostalCodeFirst3: 'Left postal-code widget before the hyphen.',
    inviterPostalCodeLast4: 'Right postal-code widget after the hyphen.',
    inviterAddress: 'Single full-width inviter address blank.',
    inviterName: 'Inviter name blank below address.',
    inviterPhone: 'Inviter telephone blank.',
    inviterExtension: 'Inviter extension blank to the right of telephone.',
    organisationName: 'Contact/organisation affiliation blank.',
    contactPersonName: 'Contact person name blank.',
    contactPhone: 'Contact telephone blank.',
    contactExtension: 'Contact extension blank to the right of telephone.',
    applicantNationality: 'Applicant nationality row.',
    applicantOccupation: 'Applicant occupation row.',
    applicantPassportName: 'Applicant passport-name blank; determined by row position, not AcroForm order.',
    applicantGenderMale: 'Left gender checkbox in the applicant name row.',
    applicantGenderFemale: 'Right gender checkbox in the applicant name row.',
    additionalApplicantsCount: '`ほか N 名` count widget; kept blank for the one-applicant MVP.',
    applicantDateOfBirthYear: 'Birth-date year blank.',
    applicantDateOfBirthMonth: 'Birth-date month blank.',
    applicantDateOfBirthDay: 'Birth-date day blank.',
    applicantAge: 'Age blank after birth date.',
    invitationPurpose: 'First narrative box.',
    invitationBackground: 'Second narrative box.',
    relationshipToApplicant: 'Third narrative box.',
  };
  return decisions[key];
}

async function main() {
  let pdfBytes: Uint8Array;
  try {
    pdfBytes = await readFile(templatePath);
  } catch {
    const missing = buildMarkdown([]);
    await mkdir(path.dirname(docsPath), { recursive: true });
    await writeFile(docsPath, missing, 'utf8');
    console.error(`PDF template was not found at ${templatePath}`);
    console.error(`Wrote ${path.relative(process.cwd(), docsPath)} with the current inspection limitation.`);
    process.exitCode = 1;
    return;
  }

  const pdfDoc = await PDFDocument.load(pdfBytes);
  const pages = pdfDoc.getPages();
  const form = pdfDoc.getForm();
  const fields = form.getFields();
  const reports = fields.flatMap((field) => {
    const widgets = (field.acroField as any).getWidgets?.() ?? [];
    return widgets.map((widget: any) => {
      const rect = rectFromWidget(widget);
      const pageRef = widget.P?.() ?? widget.dict?.lookupMaybe?.('P');
      const pageIndex = pages.findIndex((page) => page.ref === pageRef);
      return { fieldName: field.getName(), fieldType: fieldType(field), pageIndex: pageIndex >= 0 ? pageIndex : 'unknown', ...rect } satisfies WidgetReport;
    });
  });
  reports.sort((a, b) => String(a.pageIndex).localeCompare(String(b.pageIndex)) || b.y - a.y || a.x - b.x);

  console.log(buildMarkdown(reports));
  await mkdir(path.dirname(docsPath), { recursive: true });
  await writeFile(docsPath, buildMarkdown(reports), 'utf8');
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, buildOutput(fields.map((field) => field.getName())), 'utf8');
  console.log(`Updated ${path.relative(process.cwd(), outputPath)} and ${path.relative(process.cwd(), docsPath)}.`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
