import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { PDFDocument, PDFCheckBox, PDFDropdown, PDFOptionList, PDFRadioGroup, PDFTextField } from 'pdf-lib';
import type { PDFField } from 'pdf-lib';

const templatePath = path.join(process.cwd(), 'public', 'templates', 'shouhei-riyusho.pdf');
const outputPath = path.join(process.cwd(), 'src', 'lib', 'pdfFieldNames.ts');
const docsPath = path.join(process.cwd(), 'docs', 'pdf-field-inspection.md');

const semanticKeys = [
  'documentDateYear',
  'documentDateMonth',
  'documentDateDay',
  'diplomaticMission',
  'inviterPostalCodeFirst3',
  'inviterPostalCodeLast4',
  'inviterAddress',
  'inviterName',
  'inviterPhone',
  'inviterExtension',
  'organisationName',
  'contactPersonName',
  'contactPhone',
  'contactExtension',
  'applicantNationality',
  'applicantOccupation',
  'applicantPassportName',
  'applicantGenderMale',
  'applicantGenderFemale',
  'additionalApplicantsCount',
  'applicantDateOfBirthYear',
  'applicantDateOfBirthMonth',
  'applicantDateOfBirthDay',
  'applicantAge',
  'invitationPurpose',
  'invitationBackground',
  'relationshipToApplicant',
] as const;

type WidgetReport = {
  fieldName: string;
  fieldType: string;
  pageIndex: number | 'unknown';
  x: number;
  y: number;
  width: number;
  height: number;
};

function fieldType(field: PDFField) {
  if (field instanceof PDFTextField) return 'text';
  if (field instanceof PDFCheckBox) return 'checkbox';
  if (field instanceof PDFRadioGroup) return 'radio';
  if (field instanceof PDFDropdown) return 'dropdown';
  if (field instanceof PDFOptionList) return 'option-list';
  return field.constructor.name;
}

function toConstantName(fieldName: string, index: number, usedNames: Set<string>) {
  const asciiName = fieldName.normalize('NFKD').replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase();
  const baseName = asciiName.length > 0 ? asciiName : 'FIELD';
  let constantName = baseName;
  let suffix = index + 1;
  while (usedNames.has(constantName)) {
    constantName = `${baseName}_${suffix}`;
    suffix += 1;
  }
  usedNames.add(constantName);
  return constantName;
}

function buildOutput(fieldNames: string[]) {
  const entries = fieldNames.map((name) => `  ${JSON.stringify(name)},`).join('\n');
  const usedConstantNames = new Set<string>();
  const objectEntries = fieldNames.map((name, index) => `  ${toConstantName(name, index, usedConstantNames)}: ${JSON.stringify(name)},`).join('\n');
  const semanticEntries = semanticKeys.map((key) => `  ${key}: '',`).join('\n');

  return `// This file is generated by \`npm run inspect:pdf\`.
// Fill semantic mapping values only after verifying widget rectangles in docs/pdf-field-inspection.md.
// Do not guess field names or rely only on AcroForm order.

export const pdfFieldNames = [
${entries}
] as const;

export const pdfFieldNameMap = {
${objectEntries}
} as const;

export const invitationReasonPdfFields = {
${semanticEntries}
} as const;

export type PdfFieldName = (typeof pdfFieldNames)[number];
export type InvitationReasonPdfFieldKey = keyof typeof invitationReasonPdfFields;
`;
}

function rectFromWidget(widget: any) {
  const rectangle = typeof widget.getRectangle === 'function' ? widget.getRectangle() : undefined;
  if (rectangle) return rectangle;
  const rect = widget.dict?.lookup?.('Rect') ?? widget.dict?.get?.('Rect');
  const values = rect?.asArray?.().map((n: any) => n.asNumber?.() ?? Number(n));
  if (!values || values.length < 4) return { x: NaN, y: NaN, width: NaN, height: NaN };
  return { x: values[0], y: values[1], width: values[2] - values[0], height: values[3] - values[1] };
}

function buildMarkdown(reports: WidgetReport[]) {
  const rows = reports.map((r, i) => `| ${i + 1} | ${r.fieldName} | ${r.fieldType} | ${r.pageIndex} | ${r.x.toFixed(2)} | ${r.y.toFixed(2)} | ${r.width.toFixed(2)} | ${r.height.toFixed(2)} |`).join('\n');
  return `# PDF Field Inspection: 招へい理由書

Generated by \`npm run inspect:pdf\`.

## Mapping conclusions

- The PDF template file was inspected by AcroForm widget rectangle, not by field order alone.
- There is no confirmed mapping yet until a fillable template exists at \`public/templates/shouhei-riyusho.pdf\` and the rows below are reviewed against the visual PDF.
- \`documentDateEra\` is intentionally not part of the semantic model. If the visible \`令和\` text is printed in the template, only year/month/day fields should be mapped. If a future template has an era input field, document that exception here before adding a semantic key.
- \`additionalApplicantsCount\` is the \`ほか N 名\` field. The MVP always has exactly one applicant, so it must remain blank and must not be treated as gender.
- The diplomatic mission mapping must be the blank after \`在\` and before \`日本国\` if the template prints those fixed strings; in that case the sample value should be \`上海\`. If the field covers the full mission name, use \`在上海日本国総領事館\` and document the coordinates here.
- If the inviter address is shown as two AcroForm widgets, update the semantic model to \`inviterAddressLine1\` and \`inviterAddressLine2\`; otherwise keep the single \`inviterAddress\` key.

## Required semantic fields to verify

- Date: \`documentDateYear\`, \`documentDateMonth\`, \`documentDateDay\`
- Diplomatic mission: \`diplomaticMission\`
- Applicant: \`applicantNationality\`, \`applicantOccupation\`, \`applicantPassportName\`, \`applicantGenderMale\`, \`applicantGenderFemale\`, \`additionalApplicantsCount\`, \`applicantDateOfBirthYear\`, \`applicantDateOfBirthMonth\`, \`applicantDateOfBirthDay\`, \`applicantAge\`
- Inviter/organisation: \`inviterPostalCodeFirst3\`, \`inviterPostalCodeLast4\`, \`inviterAddress\`, \`inviterName\`, \`inviterPhone\`, \`inviterExtension\`, \`organisationName\`, \`contactPersonName\`, \`contactPhone\`, \`contactExtension\`
- Narrative: \`invitationPurpose\`, \`invitationBackground\`, \`relationshipToApplicant\`

## Visual order: top-to-bottom, left-to-right

| # | Field name | Type | Page | x | y | width | height |
|---:|---|---|---:|---:|---:|---:|---:|
${rows || '| | No AcroForm fields found or template missing. | | | | | | |'}
`;
}

async function main() {
  let pdfBytes: Uint8Array;
  try {
    pdfBytes = await readFile(templatePath);
  } catch {
    const missing = buildMarkdown([]);
    await mkdir(path.dirname(docsPath), { recursive: true });
    await writeFile(docsPath, missing, 'utf8');
    console.error(`PDF template was not found at ${templatePath}`);
    console.error(`Wrote ${path.relative(process.cwd(), docsPath)} with the current inspection limitation.`);
    process.exitCode = 1;
    return;
  }

  const pdfDoc = await PDFDocument.load(pdfBytes);
  const pages = pdfDoc.getPages();
  const form = pdfDoc.getForm();
  const fields = form.getFields();
  const reports = fields.flatMap((field) => {
    const widgets = (field.acroField as any).getWidgets?.() ?? [];
    return widgets.map((widget: any) => {
      const rect = rectFromWidget(widget);
      const pageRef = widget.P?.() ?? widget.dict?.lookupMaybe?.('P');
      const pageIndex = pages.findIndex((page) => page.ref === pageRef);
      return { fieldName: field.getName(), fieldType: fieldType(field), pageIndex: pageIndex >= 0 ? pageIndex : 'unknown', ...rect } satisfies WidgetReport;
    });
  });
  reports.sort((a, b) => String(a.pageIndex).localeCompare(String(b.pageIndex)) || b.y - a.y || a.x - b.x);

  console.log(buildMarkdown(reports));
  await mkdir(path.dirname(docsPath), { recursive: true });
  await writeFile(docsPath, buildMarkdown(reports), 'utf8');
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, buildOutput(fields.map((field) => field.getName())), 'utf8');
  console.log(`Updated ${path.relative(process.cwd(), outputPath)} and ${path.relative(process.cwd(), docsPath)}.`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
